#!/bin/bash
SPACK_HOME=/opt/ohpc/pub/spack
SUDO_HOME=$(eval echo ~${SUDO_USER})
BASEDIR=$(dirname $(realpath $0))
eval $(${BASEDIR}/shdotenv -e ${SUDO_HOME}/.spack_setup)

export SPACK_VER=${SPACK_VER:-v0.20.1}
export DISABLE_SYSTEM_SPACK=${DISABLE_SYSTEM_SPACK:-0}

if [ $DISABLE_SYSTEM_SPACK -eq 1 ]; then
    :
else
    . ${SPACK_HOME}/${SPACK_VER}/share/spack/setup-env.sh
fi

if [ "$1" == "install" -o \
     "$1" == "uninstall" -o \
     "$1" == "env" -o \
     "$1" == "clean" -o \
     "$1" == "spec" ]; then
    spack "$@"
fi
