#!/bin/bash
SUDO_HOME=$(eval echo ~${SUDO_USER})
#cat ${SUDO_HOME}/.spack_setup
eval $(/opt/ohpc/pub/spack/shdotenv -e ${SUDO_HOME}/.spack_setup)
#echo SPACK_VER is ${SPACK_VER}

export SPACK_VER=${SPACK_VER:-v0.19.1}
export DISABLE_SYSTEM_SPACK=${DISABLE_SYSTEM_SPACK:-0}

if [ $DISABLE_SYSTEM_SPACK -eq 1 ]; then
    :
else
    . /opt/ohpc/pub/spack/${SPACK_VER}/share/spack/setup-env.sh
fi

if [ "$1" == "install" -o "$1" == "uninstall" -o "$1" == "env" ]; then
    spack "$@"
fi
